cp ~/IdeaProjects/TribesX-Parent/TribesX/build/libs/TribesX-Core-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX-1.0.jar
cp ~/IdeaProjects/TribesX-Parent/FGrace-Addon/build/libs/FGrace-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FGrace.jar
cp ~/IdeaProjects/TribesX-Parent/FPrinter-Addon/build/libs/FPrinter-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FPrinter.jar
cp ~/IdeaProjects/TribesX-Parent/FTOP-Addon/build/libs/FTOP-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FTOP.jar
cp ~/IdeaProjects/TribesX-Parent/FTNT-Addon/build/libs/FTNT-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FTNT.jar
cp ~/IdeaProjects/TribesX-Parent/FWild-Addon/build/libs/FWild-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FWild.jar
cp ~/IdeaProjects/TribesX-Parent/FChest-Addon/build/libs/FChest-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FChest.jar
cp ~/IdeaProjects/TribesX-Parent/FRoster-Addon/build/libs/FRoster-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FRoster.jar
cp ~/IdeaProjects/TribesX-Parent/FDynmap-Addon/build/libs/FDynmap-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FDynmap.jar
cp ~/IdeaProjects/TribesX-Parent/FCropUpgrades-Addon/build/libs/FCropUpgrades-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FCropUpgrades.jar
cp ~/IdeaProjects/TribesX-Parent/FMaxTileEntities-Addon/build/libs/FMaxTileEntities-Addon-1.0.6-RC.jar ~/Servers/serverfast/plugins/TribesX/addons/FMaxTileEntities.jar
