/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "TribesX-Parent"
include(":AddonFramework")
include(":TribesX")
include("TribesUUIDAPIProxy")
include(":FTOP-Addon")
include(":FWild-Addon")
include(":FGrace-Addon")
include(":FTNT-Addon")
include(":FPrinter-Addon")
include(":FMobTweaks-Addon")
include(":FRoam-Addon")
include(":FChest-Addon")
include(":FRoster-Addon")
include(":FDynmap-Addon")
include(":FShop-Addon")
include(":FCropUpgrades-Addon")
include(":FMaxTileEntities-Addon")
include(":TribesUUIDAPIProxy")
include(":FEssentials-Addon")
